spring:
  application:
    name: miniapp-product-server
  datasource:
    username: task_mini_app
    password: dCAi4a2rrLDaREPf
    url: jdbc:mysql://39.99.136.115/task_mini_app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: lry123456
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
  pool:
    enabled: true
    max-connections: 10   #连接池最大连接数
    idle-timeout: 30000   #空闲的连接过期时间，默认为30秒

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.huiounet.miniapppojo.pojo

server:
  port: 8083
  servlet:
    context-path: /product

eureka:
  client:
    service-url:
      #defaultZone 这个是不会提示的，此处需要自己写
      #实际上属性应该是service-url,这个属性是个map（key-value）格式；当key是defaultZone的时候才能被解析；所以这里没有提示，
      #但是自己还需要写一个defaultZone；
      defaultZone: http://39.99.136.115:8081/eureka/eureka


