server:
  servlet:
    #  定义项目的访问访问路径
    context-path: /consumer
    #定义端口号
  port: 8082
spring:
  application:
    #定义应用名称，即服务名称
    name: miniapp-consumer-server
eureka:
  client:
    service-url:
      defaultZone: http://39.99.136.115:8081/eureka/eureka





